services:
    database:
            image: mariadb
            restart: always
            container_name: pp_db
            networks:
                - backend
            ports:
                - "3306:3306"
            command: --init-file /data/application/init.sql
            volumes:
                - ./init.sql:/data/application/init.sql
            environment:
                MYSQL_ROOT_PASSWORD: root
                MYSQL_DATABASE: puntportalen
                MYSQL_USER: root

    frontend:
        build: ./server/client
        volumes:
            - ./server/client/:/app
            - /app/node_modules
        container_name: pp_client
        networks:
            - frontend
        ports:
            - "5173:5173"

    backend:
        build: ./server
        volumes:
            - ./server/:/app
            - /app/node_modules
        container_name: pp_server
        networks:
            - frontend
            - backend
        ports:
            - "8082:2000"

networks:
    frontend:
    backend:
