services:
    frontend:
        build: ./client
        volumes:
            - ./client/:/app
            - /app/node_modules
        container_name: pp_client
        networks: 
            - frontend
        ports: 
            - "8081:8080"
        
    backend:
        build: ./server
        volumes:
            - ./server/:/app
            - /app/node_modules
        container_name: pp_server
        networks:
            - frontend
            - backend
        ports:
            - "8082:2000"

networks:
    frontend:
    backend:
