services:
    frontend:
        build: ./client
        volumes:
            - ./client/:/app
            - /app/node_modules
        container_name: pp_client
        networks: 
            - frontend
        ports: 
            - "8081:8080"
        
    backend:
        build: ./server
        volumes:
            - ./server/:/app
            - /app/node_modules
        container_name: pp_server
        networks:
            - frontend
            - backend
        ports:
            - "8082:2000"

    database:
        image: mariadb 
        restart: always
        container_name: pp_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: puntportalen
            MYSQL_USER: root
        networks:
            - backend
        ports:
            - "3306:3306"

networks:
    frontend:
    backend:
