const betBets = [
  {
    id: 1,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 1,
    user_id: 2,
    paid: 0,
  },
  {
    id: 2,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 1,
    user_id: 5,
    paid: 0,
  },
  {
    id: 3,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 1,
    user_id: 6,
    paid: 0,
  },
  {
    id: 4,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 1,
    user_id: 7,
    paid: 0,
  },
  {
    id: 5,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 1,
    user_id: 8,
    paid: 0,
  },
  {
    id: 6,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 1,
    user_id: 1,
    paid: 0,
  },
  {
    id: 7,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 2,
    user_id: 1,
    paid: 0,
  },
  {
    id: 8,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 2,
    user_id: 2,
    paid: 0,
  },
  {
    id: 9,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 2,
    user_id: 3,
    paid: 0,
  },
  {
    id: 10,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 2,
    user_id: 7,
    paid: 0,
  },
  {
    id: 11,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 3,
    user_id: 1,
    paid: 0,
  },
  {
    id: 12,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 3,
    user_id: 6,
    paid: 0,
  },
  {
    id: 13,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 4,
    user_id: 5,
    paid: 0,
  },
  {
    id: 14,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 4,
    user_id: 8,
    paid: 0,
  },
  {
    id: 15,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 4,
    user_id: 6,
    paid: 0,
  },
  {
    id: 16,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 4,
    user_id: 7,
    paid: 0,
  },
  {
    id: 17,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 4,
    user_id: 4,
    paid: 0,
  },
  {
    id: 18,
    created_at: new Date(),
    updated_at: new Date(),
    bet_id: 4,
    user_id: 3,
    paid: 0,
  },
];

module.exports = betBets;
