const users = [
  {
    id: 1,
    created_at: new Date(),
    updated_at: new Date(),
    email: "malm@puntportalen.se",
    first_name: "Emil",
    last_name: "Malm",
    residence: "Nedre Svedjan",
    logo: "ggg",
    team_name: "Wellsea Slopes",
    hash: "$2b$10$lVuCceB4yrBX.fULy6/as.TVrqN6NveCRtQESAShHzIcG48rFobM2",
  },
  {
    id: 2,
    created_at: new Date(),
    updated_at: new Date(),
    email: "oberg@puntportalen.se",
    first_name: "Mattias",
    last_name: "Öberg",
    residence: "Domnarvet",
    logo: "hhh",
    team_name: "Domnarvet Gaythors",
    hash: "$2b$10$bytD9usDj08dn042fMt93eleeXYDsZ32t0sNZ.FFTHsiA.wQpTpg.",
  },
  {
    id: 3,
    created_at: new Date(),
    updated_at: new Date(),
    email: "apelman@puntportalen.se",
    first_name: "Jonas",
    last_name: "Apelman",
    residence: "Hagalund",
    logo: "iii",
    team_name: "Hagalund Football Team",
    hash: "$2b$10$S2sN7RFsOiU5Nr8kPbGHreQoyKawHnMm6gF233tyTQGHR2ssTEVqy",
  },
  {
    id: 4,
    created_at: new Date(),
    updated_at: new Date(),
    email: "lindqvist@puntportalen.se",
    first_name: "Sebastian",
    last_name: "Lindqvist",
    residence: "Domnarvet",
    logo: "jjj",
    team_name: "Lady Brady",
    hash: "$2b$10$u3XZNfoH8lg9Us5Yu44Ip.CISvSJUdpNevesLlUUZJpxdGFa02KBC",
  },
  {
    id: 5,
    created_at: new Date(),
    updated_at: new Date(),
    email: "isaksson@puntportalen.se",
    first_name: "Oskar",
    last_name: "Isaksson",
    residence: "Duvnäs",
    logo: "kkk",
    team_name: "AC Pigeon Hill",
    hash: "$2b$10$WsIMAp4/1MjgQdDjNIjuVuys6.HJTr14N7rzYFyYTEQKPLe8EpL.O",
  },
  {
    id: 6,
    created_at: new Date(),
    updated_at: new Date(),
    email: "grundstrom@puntportalen.se",
    first_name: "Markus",
    last_name: "Grundström",
    residence: "Hagalund",
    logo: "lll",
    team_name: "KP Torpedo",
    hash: "$2b$10$AUMfbmYj6xqqlMVE0dcYpe2O.cTBMV7Y8bQiVZ95PB4tTfOBef/su",
  },
  {
    id: 7,
    created_at: new Date(),
    updated_at: new Date(),
    email: "korvanen@puntportalen.se",
    first_name: "Henrik",
    last_name: "Korvanen",
    residence: "Svedjan",
    logo: "mmm",
    team_name: "FC Svedjan Traktor",
    hash: "$2b$10$TnOZcllg8bYv8s5ALtCkRu3q5niRy3NbDWFAA90eqORR4InAFe2K6",
  },
  {
    id: 8,
    created_at: new Date(),
    updated_at: new Date(),
    email: "garcia@puntportalen.se",
    first_name: "Carlos",
    last_name: "Garcia",
    residence: "Dagny",
    logo: "nnn",
    team_name: "Lokomotiv Garcia",
    hash: "$2b$10$0EElSPXLUxWDxtay8Gv9PO9AcoOp949sIxHDp6d.k59RlGzEW.o0a",
  },
  {
    id: 9,
    created_at: new Date(),
    updated_at: new Date(),
    email: "sonnert@puntportalen.se",
    first_name: "Johan",
    last_name: "Sönnert",
    residence: "Torsång",
    logo: "ttt",
    team_name: "Monsters of Torsång",
    hash: "$2b$10$FNY4j6ySOZ.F6r1Im8G93ul1taYNK9BBtyTrcU/TNsLkL6uPZ/Ti.",
  },
  {
    id: 10,
    created_at: new Date(),
    updated_at: new Date(),
    email: "hinders@puntportalen.se",
    first_name: "Mattias",
    last_name: "Hinders",
    residence: "Årby",
    logo: "aaa",
    team_name: "Årby Slugs",
    hash: "$2b$10$FGAF0hUASfWYRGnoYCBsaeX6Sl3hlj5zbIDMzaIELQ/UqB0ZoFAGa",
  },
];

module.exports = users;
