const users = [
    {
        id: 1,
        created_at: new Date(),
        updated_at: new Date(),
        email: 'emil@puntportalen.se',
        first_name: 'Emil',
        last_name: 'Malm',
        residence: 'Nedre Svedjan',
        logo: 'ggg',
        team_name: 'Wellsea Slopes',
        hash: 'oiewvnj98wy45w98nev9w8enb9283b2',
    },
    {
        id: 2,
        created_at: new Date(),
        updated_at: new Date(),
        email: 'mattias@puntportalen.se',
        first_name: 'Mattias',
        last_name: 'Öberg',
        residence: 'Domnarvet',
        logo: 'hhh',
        team_name: 'Domnarvet Gaythors',
        hash: 'ljnog0285u20b3vb6gt6205o202385m',
    },
    {
        id: 3,
        created_at: new Date(),
        updated_at: new Date(),
        email: 'jonas@puntportalen.se',
        first_name: 'Jonas',
        last_name: 'Apelman',
        residence: 'Hagalund',
        logo: 'iii',
        team_name: 'Hagalund Football Team',
        hash: 'iuw5g2g8n95gj2g9825hg29387g982395',
    },
    {
        id: 4,
        created_at: new Date(),
        updated_at: new Date(),
        email: 'sebastian@puntportalen.se',
        first_name: 'Sebastian',
        last_name: 'Lindqvist',
        residence: 'Domnarvet',
        logo: 'jjj',
        team_name: 'Lady Brady',
        hash: 'g285h8gj982mb59m82589h58922n253yn7',
    },
    {
        id: 5,
        created_at: new Date(),
        updated_at: new Date(),
        email: 'oskar@puntportalen.se',
        first_name: 'Oskar',
        last_name: 'Isaksson',
        residence: 'Duvnäs',
        logo: 'kkk',
        team_name: 'AC Pigeon Hill',
        hash: 'bgn84nh9mbv8n28mbmb92msromhruony45t',
    },
    {
        id: 6,
        created_at: new Date(),
        updated_at: new Date(),
        email: 'markus@puntportalen.se',
        first_name: 'Markus',
        last_name: 'Grundström',
        residence: 'Hagalund',
        logo: 'lll',
        team_name: 'KP Torpedo',
        hash: 'bm245nmb3408mb3098mu46n30mn308unb3448',
    },
    {
        id: 7,
        created_at: new Date(),
        updated_at: new Date(),
        email: 'henrik@puntportalen.se',
        first_name: 'Henrik',
        last_name: 'Korvanen',
        residence: 'Svedjan',
        logo: 'mmm',
        team_name: 'FC Svedjan Traktor',
        hash: 'b28jum5bh2895ng2b3m029m3b092m5hnm8u2h3n8',
    },
    {
        id: 8,
        created_at: new Date(),
        updated_at: new Date(),
        email: 'carlos@puntportalen.se',
        first_name: 'Carlos',
        last_name: 'Garcia',
        residence: 'Dagny',
        logo: 'nnn',
        team_name: 'Lokomotiv Garcia',
        hash: 'aeroinu238n20395im230im25bn287y35b2b35b153',
    },
];

module.exports = users;